let mock = [{
        id: 1,
        name: "Luke Skywalker",
        height: "172",
        mass: "77",
        hair_color: "blond",
        skin_color: "fair",
        eye_color: "blue",
        birth_year: "19BBY",
        gender: "male",
        image: 'luke.jpg'

      },
      {
        id: 2,
        name: "C-3PO",
        height: "167",
        mass: "75",
        hair_color: "n/a",
        skin_color: "gold",
        eye_color: "yellow",
        birth_year: "112BBY",
        gender: "n/a",
        image: 'c3po.jpg'

      },
      {
    id: 3,
    name: "R2-D2",
    height: "96",
    mass: "32",
    hair_color: "n/a",
    skin_color: "white, blue",
    eye_color: "red",
    birth_year: "33BBY",
    gender: "n/a",
    image: 'r2d2.jpg'
      },
  {
    id: 4,
    name: "Darth Vader",
    height: "202",
    mass: "136",
    hair_color: "none",
    skin_color: "white",
    eye_color: "yellow",
    birth_year: "41.9BBY",
    gender: "male",
    image: 'vader.jpg'
},
{
    id: 5,
    name: "Leia Organa",
    height: "150",
    mass: "49",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "19BBY",
    gender: "female",
    image: 'leia.jpg'
},
{
    id: 6,
    name: "Owen Lars",
    height: "178",
    mass: "120",
    hair_color: "brown, grey",
    skin_color: "light",
    eye_color: "blue",
    birth_year: "52BBY",
    gender: "male",
    image: 'owen.png'
},
{
    id: 7,
    name: "Obi-Wan Kenobi",
    height: "182",
    mass: "77",
    hair_color: "auburn, white",
    skin_color: "fair",
    eye_color: "blue-gray",
    birth_year: "57BBY",
    gender: "male",
    image: 'obi-wan.jpg'
},
{
  id: 8,
	name: "Anakin Skywalker",
	height: "188",
	mass: "84",
	hair_color: "blond",
	skin_color: "fair",
	eye_color: "blue",
	birth_year: "41.9BBY",
	gender: "male",
  image: 'anakin.jpg'
},
{
    id: 9,
    name: "Wilhuff Tarkin",
    height: "180",
    mass: "unknown",
    hair_color: "auburn, grey",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "64BBY",
    gender: "male",
    image: 'tarkin.jpg'
  },
  {
    id: 10,
    name: "Chewbacca",
    height: "228",
    mass: "112",
    hair_color: "brown",
    skin_color: "unknown",
    eye_color: "blue",
    birth_year: "200BBY",
    gender: "male",
    image: 'chewie.jpg'
  },
  {
    id: 11,
    name: "Han Solo",
    height: "180",
    mass: "80",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "29BBY",
    gender: "male",
    image: 'han.jpg'
  },
  {
    id: 12,
    name: "Greedo",
    height: "173",
    mass: "74",
    hair_color: "n/a",
    skin_color: "green",
    eye_color: "black",
    birth_year: "44BBY",
    gender: "male",
    image: 'greedo.jpg'
  },
  {
    id: 13,
    name: "Jabba Desilijic Tiure",
    height: "175",
    mass: "1,358",
    hair_color: "n/a",
    skin_color: "green-tan, brown",
    eye_color: "orange",
    birth_year: "600BBY",
    gender: "hermaphrodite",
    image: 'jabba.jpg'
  },
  {
    id: 14,
    name: "Wedge Antilles",
    height: "170",
    mass: "77",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "hazel",
    birth_year: "21BBY",
    gender: "male",
    image: 'wedge.jpg'
  },
  {
    id: 15,
    name: "Yoda",
    height: "66",
    mass: "17",
    hair_color: "white",
    skin_color: "green",
    eye_color: "brown",
    birth_year: "896BBY",
    gender: "male",
    image: 'yoda.jpg'
  },
  {
    id: 16,
    name: "Palpatine",
    height: "170",
    mass: "75",
    hair_color: "grey",
    skin_color: "pale",
    eye_color: "yellow",
    birth_year: "82BBY",
    gender: "male",
    image: 'sheev.jpg'
  },
  {
    id: 17,
    name: "Boba Fett",
    height: "183",
    mass: "78.2",
    hair_color: "black",
    skin_color: "fair",
    eye_color: "brown",
    birth_year: "31.5BBY",
    gender: "male",
    image: 'boba.jpeg'
  },
  {
    id: 18,
    name: "Bossk",
    height: "190",
    mass: "113",
    hair_color: "none",
    skin_color: "green",
    eye_color: "red",
    birth_year: "53BBY",
    gender: "male",
    image: 'bossk.jpg'
  },
  {
    id: 19,
    name: "Lando Calrissian",
    height: "177",
    mass: "79",
    hair_color: "black",
    skin_color: "dark",
    eye_color: "brown",
    birth_year: "31BBY",
    gender: "male",
    image: 'lando.png'
  },
  {
    id: 20,
    name: "Ackbar",
    height: "180",
    mass: "83",
    hair_color: "none",
    skin_color: "brown mottle",
    eye_color: "orange",
    birth_year: "41BBY",
    gender: "male",
    image: 'ackbar.png'
  },
  {
    id: 21,
    name: "Qui-Gon Jinn",
    height: "193",
    mass: "89",
    hair_color: "brown",
    skin_color: "fair",
    eye_color: "blue",
    birth_year: "92BBY",
    gender: "male",
    image: 'qui-gon.jpg'
  },
  {
    id: 22,
    name: "Padmé Amidala",
    height: "185",
    mass: "45",
    hair_color: "brown",
    skin_color: "light",
    eye_color: "brown",
    birth_year: "46BBY",
    gender: "female",
    image: 'padme.jpg'
  },
  {
    id: 23,
    name: "Jar Jar Binks",
    height: "196",
    mass: "66",
    hair_color: "none",
    skin_color: "orange",
    eye_color: "orange",
    birth_year: "52BBY",
    gender: "male",
    image: 'jarjar.png'
  },
  {
    id: 24,
    name: "Darth Maul",
    height: "175",
    mass: "80",
    hair_color: "none",
    skin_color: "red",
    eye_color: "yellow",
    birth_year: "54BBY",
    gender: "male",
    image: 'maul.jpeg'
  }
]

export default mock;
